### PR TITLE
Added new version of msapp v3.1

### PR DESCRIPTION
**Pull request by junterpfe**
switched to using a collection for desks will support up to 2k desks
using a collection to check for conflicts to remove delegation warning should support up to 2k reservation checks within selected date range
updated patch on desk creation so that it passes the active switch in the patch
Updated filter for the double-booking check should now prevent overlapping bookings.
Added a few refreshes and clear collects to support the new collections
Blocked the ability to book time where the end time is before the start time.
Confirmation button for adding desk now shows New or Update.
If statement to prevent duplicate desks being created.
added some logic to reset the desk selection checkboxes, some data was sticking between bookings.
Added search function to Desk selection (Title and description), sorted data based on desk name.

On the SharePoint side to support delegation,
set column indexes for:
"Active" in the "Desks" list
"Check Out From", "Check Out To", "DeskText", "Title" in the "Desk Reservation" list

### CODE REVIEW

**Comment by albertocaa1317** [comment]
Hi @junterpfe,
I detected an issue in the original app and I want ask you if your version fix it.

I detected that if there is a desk is reserved in a range of days, for example, 1,2,3 December and I try to reserve the same desk in the days, 2,3 December, the desk doesn't is available. BUT if I try to reserve the same desk in the days 2,3,4 December, the desk is available! Then I can create a duplicate booking for this desk un the days 2,3 December.

Do you fix this issue?
Thanks.

**Comment by junterpfe** [comment]
When testing i was not able to commit a double booking with my version.
please give it a try and let me know if it works for you if not i will take another look at it.

**Comment by junterpfe** [comment]
I will re-test, what time zone are you in?

**Comment by albertocaa1317** [comment]
CET (Spain)

**Comment by junterpfe** [comment]
it seems to fail if my timezone is different than the sharepoint site's timezone.
In my case they were both set to est and it worked, when i set mine to UTC +1 it seems to have issues (and show the wrong times)

**Pull request merged**
